/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardRouteRouteImport } from './routes/onboard/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppNotificationsIndexRouteImport } from './routes/app/notifications/index'
import { Route as AppFeedIndexRouteImport } from './routes/app/feed/index'
import { Route as AppExploreIndexRouteImport } from './routes/app/explore/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsHelpRouteImport } from './routes/app/settings/help'
import { Route as AppSettingsBillingRouteImport } from './routes/app/settings/billing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const OnboardRouteRoute = OnboardRouteRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaintenanceRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeedIndexRoute = AppFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExploreIndexRoute = AppExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsHelpRoute = AppSettingsHelpRouteImport.update({
  id: '/settings/help',
  path: '/settings/help',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboard': typeof OnboardRouteRoute
  '/login/': typeof LoginIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/help': typeof AppSettingsHelpRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/explore': typeof AppExploreIndexRoute
  '/app/feed': typeof AppFeedIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboard': typeof OnboardRouteRoute
  '/login': typeof LoginIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/help': typeof AppSettingsHelpRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/explore': typeof AppExploreIndexRoute
  '/app/feed': typeof AppFeedIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboard': typeof OnboardRouteRoute
  '/login/': typeof LoginIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/help': typeof AppSettingsHelpRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/explore/': typeof AppExploreIndexRoute
  '/app/feed/': typeof AppFeedIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboard'
    | '/login/'
    | '/maintenance/'
    | '/api/auth/$'
    | '/app/settings/billing'
    | '/app/settings/help'
    | '/app/settings/profile'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/feed'
    | '/app/notifications'
    | '/app/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/onboard'
    | '/login'
    | '/maintenance'
    | '/api/auth/$'
    | '/app/settings/billing'
    | '/app/settings/help'
    | '/app/settings/profile'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/feed'
    | '/app/notifications'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboard'
    | '/login/'
    | '/maintenance/'
    | '/api/auth/$'
    | '/app/settings/billing'
    | '/app/settings/help'
    | '/app/settings/profile'
    | '/app/dashboard/'
    | '/app/explore/'
    | '/app/feed/'
    | '/app/notifications/'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OnboardRouteRoute: typeof OnboardRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notifications/': {
      id: '/app/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/feed/': {
      id: '/app/feed/'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/explore/': {
      id: '/app/explore/'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/settings/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/help': {
      id: '/app/settings/help'
      path: '/settings/help'
      fullPath: '/app/settings/help'
      preLoaderRoute: typeof AppSettingsHelpRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/settings/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsHelpRoute: typeof AppSettingsHelpRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppExploreIndexRoute: typeof AppExploreIndexRoute
  AppFeedIndexRoute: typeof AppFeedIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsHelpRoute: AppSettingsHelpRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppExploreIndexRoute: AppExploreIndexRoute,
  AppFeedIndexRoute: AppFeedIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OnboardRouteRoute: OnboardRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
