/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitRouteImport } from './routes/wait'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStartupsRouteRouteImport } from './routes/app/startups/route'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppNotificationsIndexRouteImport } from './routes/app/notifications/index'
import { Route as AppFeedIndexRouteImport } from './routes/app/feed/index'
import { Route as AppExploreIndexRouteImport } from './routes/app/explore/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppStartupsCreateRouteImport } from './routes/app/startups/create'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsHelpRouteImport } from './routes/app/settings/help'
import { Route as AppSettingsBillingRouteImport } from './routes/app/settings/billing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppExploreStartupsIndexRouteImport } from './routes/app/explore/startups/index'
import { Route as AppExploreSprintsIndexRouteImport } from './routes/app/explore/sprints/index'
import { Route as AppDashboardStartupNewRouteImport } from './routes/app/dashboard/startup/new'
import { Route as AppDashboardStartupSlugRouteImport } from './routes/app/dashboard/startup/$slug'

const WaitRoute = WaitRouteImport.update({
  id: '/wait',
  path: '/wait',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStartupsRouteRoute = AppStartupsRouteRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeedIndexRoute = AppFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExploreIndexRoute = AppExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStartupsCreateRoute = AppStartupsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppStartupsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsHelpRoute = AppSettingsHelpRouteImport.update({
  id: '/settings/help',
  path: '/settings/help',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExploreStartupsIndexRoute = AppExploreStartupsIndexRouteImport.update({
  id: '/explore/startups/',
  path: '/explore/startups/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExploreSprintsIndexRoute = AppExploreSprintsIndexRouteImport.update({
  id: '/explore/sprints/',
  path: '/explore/sprints/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardStartupNewRoute = AppDashboardStartupNewRouteImport.update({
  id: '/dashboard/startup/new',
  path: '/dashboard/startup/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardStartupSlugRoute = AppDashboardStartupSlugRouteImport.update({
  id: '/dashboard/startup/$slug',
  path: '/dashboard/startup/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/wait': typeof WaitRoute
  '/app/startups': typeof AppStartupsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/help': typeof AppSettingsHelpRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/startups/create': typeof AppStartupsCreateRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/explore': typeof AppExploreIndexRoute
  '/app/feed': typeof AppFeedIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/dashboard/startup/$slug': typeof AppDashboardStartupSlugRoute
  '/app/dashboard/startup/new': typeof AppDashboardStartupNewRoute
  '/app/explore/sprints': typeof AppExploreSprintsIndexRoute
  '/app/explore/startups': typeof AppExploreStartupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/wait': typeof WaitRoute
  '/app/startups': typeof AppStartupsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/help': typeof AppSettingsHelpRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/startups/create': typeof AppStartupsCreateRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/explore': typeof AppExploreIndexRoute
  '/app/feed': typeof AppFeedIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/dashboard/startup/$slug': typeof AppDashboardStartupSlugRoute
  '/app/dashboard/startup/new': typeof AppDashboardStartupNewRoute
  '/app/explore/sprints': typeof AppExploreSprintsIndexRoute
  '/app/explore/startups': typeof AppExploreStartupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/wait': typeof WaitRoute
  '/app/startups': typeof AppStartupsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/help': typeof AppSettingsHelpRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/startups/create': typeof AppStartupsCreateRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/explore/': typeof AppExploreIndexRoute
  '/app/feed/': typeof AppFeedIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/dashboard/startup/$slug': typeof AppDashboardStartupSlugRoute
  '/app/dashboard/startup/new': typeof AppDashboardStartupNewRoute
  '/app/explore/sprints/': typeof AppExploreSprintsIndexRoute
  '/app/explore/startups/': typeof AppExploreStartupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboard'
    | '/wait'
    | '/app/startups'
    | '/api/auth/$'
    | '/app/settings/billing'
    | '/app/settings/help'
    | '/app/settings/profile'
    | '/app/startups/create'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/feed'
    | '/app/notifications'
    | '/app/settings'
    | '/app/dashboard/startup/$slug'
    | '/app/dashboard/startup/new'
    | '/app/explore/sprints'
    | '/app/explore/startups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboard'
    | '/wait'
    | '/app/startups'
    | '/api/auth/$'
    | '/app/settings/billing'
    | '/app/settings/help'
    | '/app/settings/profile'
    | '/app/startups/create'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/feed'
    | '/app/notifications'
    | '/app/settings'
    | '/app/dashboard/startup/$slug'
    | '/app/dashboard/startup/new'
    | '/app/explore/sprints'
    | '/app/explore/startups'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboard'
    | '/wait'
    | '/app/startups'
    | '/api/auth/$'
    | '/app/settings/billing'
    | '/app/settings/help'
    | '/app/settings/profile'
    | '/app/startups/create'
    | '/app/dashboard/'
    | '/app/explore/'
    | '/app/feed/'
    | '/app/notifications/'
    | '/app/settings/'
    | '/app/dashboard/startup/$slug'
    | '/app/dashboard/startup/new'
    | '/app/explore/sprints/'
    | '/app/explore/startups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  WaitRoute: typeof WaitRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wait': {
      id: '/wait'
      path: '/wait'
      fullPath: '/wait'
      preLoaderRoute: typeof WaitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/startups': {
      id: '/app/startups'
      path: '/startups'
      fullPath: '/app/startups'
      preLoaderRoute: typeof AppStartupsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notifications/': {
      id: '/app/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/feed/': {
      id: '/app/feed/'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/explore/': {
      id: '/app/explore/'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/startups/create': {
      id: '/app/startups/create'
      path: '/create'
      fullPath: '/app/startups/create'
      preLoaderRoute: typeof AppStartupsCreateRouteImport
      parentRoute: typeof AppStartupsRouteRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/settings/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/help': {
      id: '/app/settings/help'
      path: '/settings/help'
      fullPath: '/app/settings/help'
      preLoaderRoute: typeof AppSettingsHelpRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/settings/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/explore/startups/': {
      id: '/app/explore/startups/'
      path: '/explore/startups'
      fullPath: '/app/explore/startups'
      preLoaderRoute: typeof AppExploreStartupsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/explore/sprints/': {
      id: '/app/explore/sprints/'
      path: '/explore/sprints'
      fullPath: '/app/explore/sprints'
      preLoaderRoute: typeof AppExploreSprintsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/startup/new': {
      id: '/app/dashboard/startup/new'
      path: '/dashboard/startup/new'
      fullPath: '/app/dashboard/startup/new'
      preLoaderRoute: typeof AppDashboardStartupNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/startup/$slug': {
      id: '/app/dashboard/startup/$slug'
      path: '/dashboard/startup/$slug'
      fullPath: '/app/dashboard/startup/$slug'
      preLoaderRoute: typeof AppDashboardStartupSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppStartupsRouteRouteChildren {
  AppStartupsCreateRoute: typeof AppStartupsCreateRoute
}

const AppStartupsRouteRouteChildren: AppStartupsRouteRouteChildren = {
  AppStartupsCreateRoute: AppStartupsCreateRoute,
}

const AppStartupsRouteRouteWithChildren =
  AppStartupsRouteRoute._addFileChildren(AppStartupsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppStartupsRouteRoute: typeof AppStartupsRouteRouteWithChildren
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsHelpRoute: typeof AppSettingsHelpRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppExploreIndexRoute: typeof AppExploreIndexRoute
  AppFeedIndexRoute: typeof AppFeedIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppDashboardStartupSlugRoute: typeof AppDashboardStartupSlugRoute
  AppDashboardStartupNewRoute: typeof AppDashboardStartupNewRoute
  AppExploreSprintsIndexRoute: typeof AppExploreSprintsIndexRoute
  AppExploreStartupsIndexRoute: typeof AppExploreStartupsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppStartupsRouteRoute: AppStartupsRouteRouteWithChildren,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsHelpRoute: AppSettingsHelpRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppExploreIndexRoute: AppExploreIndexRoute,
  AppFeedIndexRoute: AppFeedIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppDashboardStartupSlugRoute: AppDashboardStartupSlugRoute,
  AppDashboardStartupNewRoute: AppDashboardStartupNewRoute,
  AppExploreSprintsIndexRoute: AppExploreSprintsIndexRoute,
  AppExploreStartupsIndexRoute: AppExploreStartupsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  WaitRoute: WaitRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
