/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedOnboardRouteRouteImport } from './routes/(authenticated)/onboard/route'
import { Route as authenticatedARouteRouteImport } from './routes/(authenticated)/a/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedOnboardUserTypeRouteImport } from './routes/(authenticated)/onboard/user-type'
import { Route as authenticatedOnboardNameRouteImport } from './routes/(authenticated)/onboard/name'
import { Route as authenticatedOnboardLocationRouteImport } from './routes/(authenticated)/onboard/location'
import { Route as authenticatedASettingsIndexRouteImport } from './routes/(authenticated)/a/settings/index'
import { Route as authenticatedANotificationsIndexRouteImport } from './routes/(authenticated)/a/notifications/index'
import { Route as authenticatedAFeedIndexRouteImport } from './routes/(authenticated)/a/feed/index'
import { Route as authenticatedAExploreIndexRouteImport } from './routes/(authenticated)/a/explore/index'
import { Route as authenticatedADashboardIndexRouteImport } from './routes/(authenticated)/a/dashboard/index'
import { Route as authenticatedASettingsProfileRouteImport } from './routes/(authenticated)/a/settings/profile'
import { Route as authenticatedASettingsHelpRouteImport } from './routes/(authenticated)/a/settings/help'
import { Route as authenticatedASettingsBillingRouteImport } from './routes/(authenticated)/a/settings/billing'

const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/(auth-pages)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedOnboardRouteRoute =
  authenticatedOnboardRouteRouteImport.update({
    id: '/onboard',
    path: '/onboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedARouteRoute = authenticatedARouteRouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedOnboardUserTypeRoute =
  authenticatedOnboardUserTypeRouteImport.update({
    id: '/user-type',
    path: '/user-type',
    getParentRoute: () => authenticatedOnboardRouteRoute,
  } as any)
const authenticatedOnboardNameRoute =
  authenticatedOnboardNameRouteImport.update({
    id: '/name',
    path: '/name',
    getParentRoute: () => authenticatedOnboardRouteRoute,
  } as any)
const authenticatedOnboardLocationRoute =
  authenticatedOnboardLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => authenticatedOnboardRouteRoute,
  } as any)
const authenticatedASettingsIndexRoute =
  authenticatedASettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)
const authenticatedANotificationsIndexRoute =
  authenticatedANotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)
const authenticatedAFeedIndexRoute = authenticatedAFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => authenticatedARouteRoute,
} as any)
const authenticatedAExploreIndexRoute =
  authenticatedAExploreIndexRouteImport.update({
    id: '/explore/',
    path: '/explore/',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)
const authenticatedADashboardIndexRoute =
  authenticatedADashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)
const authenticatedASettingsProfileRoute =
  authenticatedASettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)
const authenticatedASettingsHelpRoute =
  authenticatedASettingsHelpRouteImport.update({
    id: '/settings/help',
    path: '/settings/help',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)
const authenticatedASettingsBillingRoute =
  authenticatedASettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/maintenance': typeof MaintenanceRoute
  '/a': typeof authenticatedARouteRouteWithChildren
  '/onboard': typeof authenticatedOnboardRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/onboard/location': typeof authenticatedOnboardLocationRoute
  '/onboard/name': typeof authenticatedOnboardNameRoute
  '/onboard/user-type': typeof authenticatedOnboardUserTypeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/a/settings/billing': typeof authenticatedASettingsBillingRoute
  '/a/settings/help': typeof authenticatedASettingsHelpRoute
  '/a/settings/profile': typeof authenticatedASettingsProfileRoute
  '/a/dashboard': typeof authenticatedADashboardIndexRoute
  '/a/explore': typeof authenticatedAExploreIndexRoute
  '/a/feed': typeof authenticatedAFeedIndexRoute
  '/a/notifications': typeof authenticatedANotificationsIndexRoute
  '/a/settings': typeof authenticatedASettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/maintenance': typeof MaintenanceRoute
  '/a': typeof authenticatedARouteRouteWithChildren
  '/onboard': typeof authenticatedOnboardRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/onboard/location': typeof authenticatedOnboardLocationRoute
  '/onboard/name': typeof authenticatedOnboardNameRoute
  '/onboard/user-type': typeof authenticatedOnboardUserTypeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/a/settings/billing': typeof authenticatedASettingsBillingRoute
  '/a/settings/help': typeof authenticatedASettingsHelpRoute
  '/a/settings/profile': typeof authenticatedASettingsProfileRoute
  '/a/dashboard': typeof authenticatedADashboardIndexRoute
  '/a/explore': typeof authenticatedAExploreIndexRoute
  '/a/feed': typeof authenticatedAFeedIndexRoute
  '/a/notifications': typeof authenticatedANotificationsIndexRoute
  '/a/settings': typeof authenticatedASettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/maintenance': typeof MaintenanceRoute
  '/(authenticated)/a': typeof authenticatedARouteRouteWithChildren
  '/(authenticated)/onboard': typeof authenticatedOnboardRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(authenticated)/onboard/location': typeof authenticatedOnboardLocationRoute
  '/(authenticated)/onboard/name': typeof authenticatedOnboardNameRoute
  '/(authenticated)/onboard/user-type': typeof authenticatedOnboardUserTypeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(authenticated)/a/settings/billing': typeof authenticatedASettingsBillingRoute
  '/(authenticated)/a/settings/help': typeof authenticatedASettingsHelpRoute
  '/(authenticated)/a/settings/profile': typeof authenticatedASettingsProfileRoute
  '/(authenticated)/a/dashboard/': typeof authenticatedADashboardIndexRoute
  '/(authenticated)/a/explore/': typeof authenticatedAExploreIndexRoute
  '/(authenticated)/a/feed/': typeof authenticatedAFeedIndexRoute
  '/(authenticated)/a/notifications/': typeof authenticatedANotificationsIndexRoute
  '/(authenticated)/a/settings/': typeof authenticatedASettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/maintenance'
    | '/a'
    | '/onboard'
    | '/login'
    | '/onboard/location'
    | '/onboard/name'
    | '/onboard/user-type'
    | '/api/auth/$'
    | '/a/settings/billing'
    | '/a/settings/help'
    | '/a/settings/profile'
    | '/a/dashboard'
    | '/a/explore'
    | '/a/feed'
    | '/a/notifications'
    | '/a/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/maintenance'
    | '/a'
    | '/onboard'
    | '/login'
    | '/onboard/location'
    | '/onboard/name'
    | '/onboard/user-type'
    | '/api/auth/$'
    | '/a/settings/billing'
    | '/a/settings/help'
    | '/a/settings/profile'
    | '/a/dashboard'
    | '/a/explore'
    | '/a/feed'
    | '/a/notifications'
    | '/a/settings'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/demo'
    | '/maintenance'
    | '/(authenticated)/a'
    | '/(authenticated)/onboard'
    | '/(auth-pages)/login'
    | '/(authenticated)/onboard/location'
    | '/(authenticated)/onboard/name'
    | '/(authenticated)/onboard/user-type'
    | '/api/auth/$'
    | '/(authenticated)/a/settings/billing'
    | '/(authenticated)/a/settings/help'
    | '/(authenticated)/a/settings/profile'
    | '/(authenticated)/a/dashboard/'
    | '/(authenticated)/a/explore/'
    | '/(authenticated)/a/feed/'
    | '/(authenticated)/a/notifications/'
    | '/(authenticated)/a/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  MaintenanceRoute: typeof MaintenanceRoute
  authPagesLoginRoute: typeof authPagesLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/onboard': {
      id: '/(authenticated)/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof authenticatedOnboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/a': {
      id: '/(authenticated)/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof authenticatedARouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/onboard/user-type': {
      id: '/(authenticated)/onboard/user-type'
      path: '/user-type'
      fullPath: '/onboard/user-type'
      preLoaderRoute: typeof authenticatedOnboardUserTypeRouteImport
      parentRoute: typeof authenticatedOnboardRouteRoute
    }
    '/(authenticated)/onboard/name': {
      id: '/(authenticated)/onboard/name'
      path: '/name'
      fullPath: '/onboard/name'
      preLoaderRoute: typeof authenticatedOnboardNameRouteImport
      parentRoute: typeof authenticatedOnboardRouteRoute
    }
    '/(authenticated)/onboard/location': {
      id: '/(authenticated)/onboard/location'
      path: '/location'
      fullPath: '/onboard/location'
      preLoaderRoute: typeof authenticatedOnboardLocationRouteImport
      parentRoute: typeof authenticatedOnboardRouteRoute
    }
    '/(authenticated)/a/settings/': {
      id: '/(authenticated)/a/settings/'
      path: '/settings'
      fullPath: '/a/settings'
      preLoaderRoute: typeof authenticatedASettingsIndexRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/notifications/': {
      id: '/(authenticated)/a/notifications/'
      path: '/notifications'
      fullPath: '/a/notifications'
      preLoaderRoute: typeof authenticatedANotificationsIndexRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/feed/': {
      id: '/(authenticated)/a/feed/'
      path: '/feed'
      fullPath: '/a/feed'
      preLoaderRoute: typeof authenticatedAFeedIndexRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/explore/': {
      id: '/(authenticated)/a/explore/'
      path: '/explore'
      fullPath: '/a/explore'
      preLoaderRoute: typeof authenticatedAExploreIndexRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/dashboard/': {
      id: '/(authenticated)/a/dashboard/'
      path: '/dashboard'
      fullPath: '/a/dashboard'
      preLoaderRoute: typeof authenticatedADashboardIndexRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/settings/profile': {
      id: '/(authenticated)/a/settings/profile'
      path: '/settings/profile'
      fullPath: '/a/settings/profile'
      preLoaderRoute: typeof authenticatedASettingsProfileRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/settings/help': {
      id: '/(authenticated)/a/settings/help'
      path: '/settings/help'
      fullPath: '/a/settings/help'
      preLoaderRoute: typeof authenticatedASettingsHelpRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/settings/billing': {
      id: '/(authenticated)/a/settings/billing'
      path: '/settings/billing'
      fullPath: '/a/settings/billing'
      preLoaderRoute: typeof authenticatedASettingsBillingRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
  }
}

interface authenticatedARouteRouteChildren {
  authenticatedASettingsBillingRoute: typeof authenticatedASettingsBillingRoute
  authenticatedASettingsHelpRoute: typeof authenticatedASettingsHelpRoute
  authenticatedASettingsProfileRoute: typeof authenticatedASettingsProfileRoute
  authenticatedADashboardIndexRoute: typeof authenticatedADashboardIndexRoute
  authenticatedAExploreIndexRoute: typeof authenticatedAExploreIndexRoute
  authenticatedAFeedIndexRoute: typeof authenticatedAFeedIndexRoute
  authenticatedANotificationsIndexRoute: typeof authenticatedANotificationsIndexRoute
  authenticatedASettingsIndexRoute: typeof authenticatedASettingsIndexRoute
}

const authenticatedARouteRouteChildren: authenticatedARouteRouteChildren = {
  authenticatedASettingsBillingRoute: authenticatedASettingsBillingRoute,
  authenticatedASettingsHelpRoute: authenticatedASettingsHelpRoute,
  authenticatedASettingsProfileRoute: authenticatedASettingsProfileRoute,
  authenticatedADashboardIndexRoute: authenticatedADashboardIndexRoute,
  authenticatedAExploreIndexRoute: authenticatedAExploreIndexRoute,
  authenticatedAFeedIndexRoute: authenticatedAFeedIndexRoute,
  authenticatedANotificationsIndexRoute: authenticatedANotificationsIndexRoute,
  authenticatedASettingsIndexRoute: authenticatedASettingsIndexRoute,
}

const authenticatedARouteRouteWithChildren =
  authenticatedARouteRoute._addFileChildren(authenticatedARouteRouteChildren)

interface authenticatedOnboardRouteRouteChildren {
  authenticatedOnboardLocationRoute: typeof authenticatedOnboardLocationRoute
  authenticatedOnboardNameRoute: typeof authenticatedOnboardNameRoute
  authenticatedOnboardUserTypeRoute: typeof authenticatedOnboardUserTypeRoute
}

const authenticatedOnboardRouteRouteChildren: authenticatedOnboardRouteRouteChildren =
  {
    authenticatedOnboardLocationRoute: authenticatedOnboardLocationRoute,
    authenticatedOnboardNameRoute: authenticatedOnboardNameRoute,
    authenticatedOnboardUserTypeRoute: authenticatedOnboardUserTypeRoute,
  }

const authenticatedOnboardRouteRouteWithChildren =
  authenticatedOnboardRouteRoute._addFileChildren(
    authenticatedOnboardRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedARouteRoute: typeof authenticatedARouteRouteWithChildren
  authenticatedOnboardRouteRoute: typeof authenticatedOnboardRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedARouteRoute: authenticatedARouteRouteWithChildren,
  authenticatedOnboardRouteRoute: authenticatedOnboardRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  MaintenanceRoute: MaintenanceRoute,
  authPagesLoginRoute: authPagesLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
